print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/youjinsong/Documents/GameLab_Environment/Walking simulator/Assets/Aquarium.mb"`)
{		
	file -o "/Users/youjinsong/Documents/GameLab_Environment/Walking simulator/Assets/Aquarium.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/youjinsong/Documents/GameLab_Environment/Walking simulator/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/youjinsong/Documents/GameLab_Environment/Walking simulator/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/youjinsong/Documents/GameLab_Environment/Walking simulator/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
